### ISSUE TITLE
修改RunTraceOpen宏

### ISSUE THREAD

**Issue by roshanman** [sx1989827/RunTrace#2]
·因为这个工具是给开发者调试用的，所以正式发布的时候肯定是需要禁用的，禁用不需要移除文件，在RunTrace.h里将RunTraceOpen宏的值改为0即可。

我认为应该将RunTraceOpen宏根据当前编译条件自动设定on/off。
# if DEBUG

```
#define RunTraceOpen 1
```
# else

```
#define RunTraceOpen 0
```
# endif

**Comment by sx1989827** [comment]
恩 说的非常好 我会修改的  谢谢
